repos:
-   repo: https://github.com/google/yapf.git
    rev: v0.43.0
    hooks:
    -   id: yapf
        additional_dependencies: [toml]
-   repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v6.0.0
    hooks:
    -   id: trailing-whitespace
        exclude: \.fits
    -   id: end-of-file-fixer
        exclude: \.fits
    -   id: check-yaml
    -   id: debug-statements
    -   id: name-tests-test
        exclude: conftestaux/
    -   id: requirements-txt-fixer
-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v22.1.1
    hooks:
    -   id: clang-format
